#include <TPO.h>

void InicLED ( void )
{
	SetDIR(RGBR, SALIDA);
	SetDIR(RGBG, SALIDA);
	SetDIR(RGBB, SALIDA);
	SetDIR(LEDLPC_R, SALIDA);
	SetDIR(LEDLPC_G, SALIDA);
	SetDIR(LEDLPC_B, SALIDA);
	SetDIR(LED1, SALIDA);
	SetDIR(LED2, SALIDA);
	SetDIR(LED3, SALIDA);
	SetDIR(LED4, SALIDA);
	SetDIR(BUZZ, SALIDA);

	SetPIN(RGBR, OFF);
	SetPIN(RGBG, OFF);
	SetPIN(RGBB, OFF);
	SetPIN(LEDLPC_R, LEDLPC_OFF);
	SetPIN(LEDLPC_G, LEDLPC_OFF);
	SetPIN(LEDLPC_B, LEDLPC_OFF);
	SetPIN(LED1, OFF);
	SetPIN(LED2, OFF);
	SetPIN(LED3, OFF);
	SetPIN(LED4, OFF);
	SetPIN(BUZZ, BUZZ_OFF);
}
